### ISSUE TITLE
warning: initializer does not fit or is out of range

### ISSUE THREAD

**Issue by johnsonjh** [dmsc/emu2#100]
This is from Oracle Developer Studio C/C++ on Linux, but some other platforms/compiler combinations give similar equivalent warnings:

```sh
"src/keyb.c", line 236: warning: initializer does not fit or is out of range: 255
"src/keyb.c", line 245: warning: initializer does not fit or is out of range: 255
"src/keyb.c", line 325: warning: initializer does not fit or is out of range: 255        
"src/keyb.c", line 342: warning: initializer does not fit or is out of range: 255
"src/keyb.c", line 349: warning: initializer does not fit or is out of range: 255
"src/keyb.c", line 349: warning: initializer does not fit or is out of range: 255
"src/keyb.c", line 357: warning: initializer does not fit or is out of range: 255
"src/keyb.c", line 357: warning: initializer does not fit or is out of range: 255
"src/keyb.c", line 357: warning: initializer does not fit or is out of range: 255
```

The warning is correct since a char is being assigned 255 and the range for char (defaults here to signed char) is -128 to 127.  Seems that sometimes char is signed and sometimes char is unsigned.  There is no standard for it, and it depends completely on the compiler and the platform.

There are various compiler specific ways to force char to be signed or unsigned (`-xchar=unsigned` for Oracle, `-qchars=unsigned` for XLC, `-funsigned-char` for GCC and Clang, `/J` for MSVC, etc.) but every one is different.

It might make sense rework this to eliminate the warnings.

**Comment by dmsc** [comment]
The C standard says:
```
In an implementation in which type char has the same range of
values as signed char, the integer character constant '\xFF' has the value −1; if type char has the
same range of values as unsigned char, the character constant '\xFF' has the value +255
```

So, a solution is to simply use `'\xFF'` instead of `0xFF` in the source.

Can you test if this silences this warning?

Thanks!

**Comment by johnsonjh** [comment]
@dmsc Yes, I tested it and that does eliminate the warnings!

**Comment by johnsonjh** [comment]
@dmsc opened PR #105

also, I didn’t know this trick… learn something new every day!
