### ISSUE TITLE
Adding Parent PSP to New PSP Creation

### ISSUE THREAD

**Issue by tsupplis** [dmsc/emu2#11]
Hello,

Following up on your todo:

```
        debug(debug_dos, "\toriginal PSP segment %04x.\n", get_current_PSP());
        debug(debug_dos, "\toriginal PSP size %02x%02x.\n", orig[7], orig[6]);
        // TODO: Initialize PSP values: int 22h, 23h, 24h and parent PSP segment to 0
        break;
    }
 ```
1.  Aren't the int values already there because of the copy we do from the initial PSP
2. Would setting the Parent PSP be

```
         new_base[16] = (get_current_PSP()&0xFF);
         new_base[17] = ((get_current_PSP()>>8)&0xFF);
```

**Comment by dmsc** [comment]
Hi!

> Hello,
> 
> Following up on your todo:
> 
> ```
>         debug(debug_dos, "\toriginal PSP segment %04x.\n", get_current_PSP());
>         debug(debug_dos, "\toriginal PSP size %02x%02x.\n", orig[7], orig[6]);
>         // TODO: Initialize PSP values: int 22h, 23h, 24h and parent PSP segment to 0
>         break;
>     }
> ```
> 
> 1. Aren't the int values already there because of the copy we do from the initial PSP

Yes, you probably are right.

> 2. Would setting the Parent PSP be
> 
> ```
>          new_base[16] = (get_current_PSP()&0xFF);
>          new_base[17] = ((get_current_PSP()>>8)&0xFF);
> ```

The reason I did not implement that is because the intlist ( http://www.ctyme.com/intr/rb-2682.htm ) says:
```
--------D-2126-------------------------------
INT 21 - DOS 1+ - CREATE NEW PROGRAM SEGMENT PREFIX
	AH = 26h
	DX = segment at which to create PSP (see #01378)
Return: AL destroyed
Notes:	new PSP is updated with memory size information; INTs 22h, 23h, 24h
	  taken from interrupt vector table; the parent PSP field is set to 0
	(DOS 2+) DOS assumes that the caller's CS is the segment of the PSP to
	  copy
```

So, perhaps the field should be set to 0?

**Comment by tsupplis** [comment]
The best way is to test 😀  ... let me do a quick try and see what dos puts.

**Comment by tsupplis** [comment]
So the value of the parent PSP initialized on int 21h, fn 26h is the value of the parent PSP of the current process. I checked on dos 7 and 2.1.
let say, your PSP is 0xE419 (Which is probably the command.com ...) this value is both the value of the parent PSP of the current PSP and the value of the new PSP, not 0.
so in our case ... as the parent psp is set to 0... it should be set to 0 too I suppose.

the suggestion I gave you above is incorrect so. This is done anyway by the psp copy already and there is nothing more to do.

**Comment by andrewbird** [comment]
Parent PSP zeroing on int21/26 was found to be the cause of the Alphawaves game failing to start when using FDPP. This issue  https://github.com/dosemu2/fdpp/issues/112 is long and contains theories and unconnected problems found within Dosemu2, but the ultimate conclusion is that PSP parent shouldn't be zeroed. 

This link shows what OpenDOS does for int21/26 https://github.com/the-grue/OpenDOS/blob/e8be6acdf8bdaa10ba87e98e789d3762515fb345/IBMDOS/PROCESS.A86#L124-L143

And a simple patch now applied to FreeDOS https://github.com/FDOS/kernel/commit/de7f0d6489e03b987b71b196eaf7135143111679

I'm not sure if it helps your discussion or not, but I thought I'd mention it.
