### ISSUE TITLE
Time to create a release of this software ?

### ISSUE THREAD

**Issue by rkeene** [dmsc/emu2#15]
Judging based solely on the screenshots, is it time to create a release of this software ?

Having a release is helpful because there is then a release version number to refer to, which can be sorted to determine when newer versions are available for package maintainers.

**Comment by dmsc** [comment]
Yes, it is probably a good idea, will work on it on the weekend.

What this emulator lacks is a good test-suite to ensure a proper release workflow.

**Comment by dmsc** [comment]
Added a release - closed.
