### ISSUE TITLE
signal.h to allow compilation on Mac

### ISSUE THREAD

**Issue by tsupplis** [dmsc/emu2#2]
Here are outputs of compilation on macosx:

src/dis.c:850:1: warning: control may reach end of non-void function
      [-Wreturn-type]
}
^
1 warning generated.
gcc -O3 -flto -Wall -g -Werror=implicit-function-declaration -Werror=int-conversion -c -o obj/dos.o src/dos.c
src/dos.c:811:13: error: implicit declaration of function 'raise' is invalid in
      C99 [-Werror,-Wimplicit-function-declaration]
            raise(SIGABRT);

simply adding signal.h to dos.c sorts out compatibility.

**Comment by dmsc** [comment]
Thank you, added the missing header.

Have Fun!
