### ISSUE TITLE
[Not an issue] You saved my day.

### ISSUE THREAD

**Issue by ivan-avalos** [dmsc/emu2#21]
Thanks for creating this wonderful tool! I was desperately searching for something I could use to easily emulate DOS programs for 8086 (similar to EMU8086, but libre), and this is just perfect. It implements basic interrupts for DOS API and runs executable files directly without having to run a whole IBM PC emulator or else.

I'm using JWASM to create DOS compatible executable files, and EMU2 to run them. The combination is simply perfect!

**Comment by dmsc** [comment]
> Thanks for creating this wonderful tool! I was desperately searching for something I could use to easily emulate DOS programs for 8086 (similar to EMU8086, but libre), and this is just perfect. It implements basic interrupts for DOS API and runs executable files directly without having to run a whole IBM PC emulator or else.

Thank you!

If you find any errors or unsupported DOS call, please help by filling bug reports.

Have Fun!
