### ISSUE TITLE
Append Capacity Request

### ISSUE THREAD

**Issue by tsupplis** [dmsc/emu2#25]
Hello, for old dos 1.x software, there is a regular need to do without disks and paths. Append on dos is a saving grace. I am happy to give it a go and propose a pull request/or put in a fork for scrutiny if you are interested.

Something like: 
```
EMU2_APPEND=[<dos-path>];[<dos-path>] emu2 ...
```

Any recommendation? I see you are very thorough in your coding style and efficiency. I would by happy to follow any rules.

The simplest naive way would be to treat the case at dos_open_file / dos_open_file_fcb or embed it with  dos_unix_path / dos_unix_path_fcb adding an append dos api...

1. create flag ignores append
2. the path needs to be 'naked', i.e. no drive decoration/path
3. a single path in EM2_APPEND would go a long way

What do you think?

**Comment by dmsc** [comment]
Hi!

This is a great idea. I normally use different drives pointing to folders, but this would simplify usage of some programs.

I think that the implementation should be similar to the APPEND command in (free-)DOS, I'm looking at https://github.com/FDOS/append/tree/master/source and they patch functions 0x0f, 0x23, 0x3d, but there are some questions:

- I don't thing that the "/X" option needs to be implemented, as PATH searching is more usefull.
- Paths in the environment variable could be DOS or UNIX paths. DOS is simpler, but UNIX could be more versatile.
- It would be easier to simply append the paths to any DOS path that does not start with "\", by retrying opening the file with different working-directories - as the FreeDOS implementation does.

Any comments?

**Comment by tsupplis** [comment]
It is more ambitious but more fun...Q: do we use the standard calls? The append of freedom seems to deviate a tiny bit.

I am using this little wrapper as a reference client. It just enables disable append on a per call basis:

[dos1exec.c.zip](https://github.com/dmsc/emu2/files/7357249/dos1exec.c.zip)

Install check (Function 00) usage
```
            mov ax,0xB700
            int 0x2F
            mov append_rc,al
 ```

Get Path Buffer (Function 04) usage
```
            push di
            push es 
            mov ax,0xB704
            int 0x2F
            mov append_seg,es 
            mov append_offset,di
            pop es 
            pop di
 ```

The set/get state is I am not sure of their usefulness but easy to implement.

So do we fully take an install approach or just implement the functions available in 2f?

**Comment by dmsc** [comment]
I found two bugs in your implementation.

Testing the DOS 3.3 append and it behaves as if the path is prepended to the original path:
- if APPEND=XX, and you are inside C:\YY, DOS search first inside C:\YY and then inside C:\YY\XX,
- if APPEND=C:\XX, and you are inside C:\YY, DOS search first inside C:\YY and then inside C:\XX.

But, in your implementation, dos_unix_path always search from the root directory, and in dos_unix_path_fcb you replace the current-working-director.

I will rewrite the functions to implement the DOS-3.3 behaviour.

**Comment by tsupplis** [comment]
Thank you so much. Super cool. All the regressions work on my side.
