### ISSUE TITLE
Small change for OSX (no /proc)

### ISSUE THREAD

**Issue by tsupplis** [dmsc/emu2#3]
Here is a suggestion for macOS support

dos.c:796

#if defined(__APPLE__) && defined(__MACH__)
        uint32_t length=4096;
        int _NSGetExecutablePath(char * buf, uint32_t * length);
        if(_NSGetExecutablePath(exe_path,&length))
            print_error("can't get emulator path.\n");
#else
        if(readlink("/proc/self/exe", exe_path, 4096) == -1)
            print_error("can't get emulator path.\n");
#endif

**Comment by dmsc** [comment]
Please, review my pull request #4 , if it works OK I will merge it.
