### ISSUE TITLE
Video output corrupted on big-endian platforms

### ISSUE THREAD

**Issue by johnsonjh** [dmsc/emu2#32]
Example of expected output:

![image](https://user-images.githubusercontent.com/61629094/148912450-1c288589-6306-42fd-9445-b494a9a21dc4.jpeg)

Actual output:

![image](https://user-images.githubusercontent.com/61629094/148912517-4578568b-4347-4d07-b44c-68c73c35a96d.jpeg)

A fix is likely trivial but I've not yet had a moment to look myself.

**Comment by johnsonjh** [comment]
I should add that the simulation works fine other than the inability to see the output...

![image](https://user-images.githubusercontent.com/61629094/148913363-ba151db6-3e22-42e1-b457-22e803234c0d.jpeg)

**Comment by johnsonjh** [comment]
I "fixed" it — at least partially ... there are likely more places swapping would be needed - I am not at all familiar with the code yet.

![image](https://user-images.githubusercontent.com/61629094/148917856-165f4a44-578a-4973-ac4d-ee2213b846e5.jpeg)

I think runtime endian detection would be the best option here - tell me what you think.

**Comment by johnsonjh** [comment]
Well, not complete but but close ...

**Comment by dmsc** [comment]
Hi!

Thanks for your report.

Can you test this branch, it has a fix for this issue: https://github.com/dmsc/emu2/tree/fix-issue-32

Have Fun!

**Comment by johnsonjh** [comment]
Sorry for the delay - yes, I can confirm that this works great.

Thanks for the quick proper solution.

**Comment by dmsc** [comment]
Thanks, merged.
