### ISSUE TITLE
FCB sequential read does not seem to advance read pointer when AL returns 3

### ISSUE THREAD

**Issue by nero** [dmsc/emu2#33]
Hello,

im running emu2 `v2021.01-20-g40101bd` (master branch at the moment of writing this).

I am opening and reading a file using the FCB syscalls `0fH` and `014H`. While iterating the file, the reads in the middle of the file return `AL=0` as expected. Upon encountering the last record, which is a partial record (because the filesize on FAT can be a non-multiple of the record size), the DTA is filled with the data, correctly padded with zero, and `AL=3` is returned.

**Expected result**: Upon the next read, EOF is signalled via `AL=1`

**Real result**: Upon the next read, the same partial record is written to the DTA again (overwriting, not just leaving untouched), and `AL=3` is returned again.

This behavior seems to be in the realm of [dos_rw_record_fcb](https://github.com/dmsc/emu2/blob/40101bdfa33ff083882e261e1a56bc528949658b/src/dos.c#L350). This function looks like it was written with the intent equal to my expectations, but i am not able to figure out why it behaves differently.

DEBUG=dos outputs:

```
D-211A20: set DTA         BX=031F CX:0000 DX:0080 DI=0327 DS:0087 ES:0087
D-210F20: open fcb        BX=031F CX:0000 DX:005C DI=0327 DS:0087 ES:0087
        convert dos fcb name C:'HELLO   LST'
        temp name '\HELLO.LST'
        open fcb './/hello.lst', 'r+b', 0005 OK.
        FCB:[d=00:n=HELLO   .LST:bn=0000:rs=0080:fs=00000379:h=0005:rn=00:ra=09000000]
D-211400: read fcb        BX=031F CX:0000 DX:005C DI=0327 DS:0087 ES:0087
        FCB:[d=00:n=HELLO   .LST:bn=0000:rs=0080:fs=00000379:h=0005:rn=00:ra=09000000]
D-211468: read fcb        BX=031F CX:0000 DX:005C DI=0327 DS:0087 ES:0087
        FCB:[d=00:n=HELLO   .LST:bn=0000:rs=0080:fs=00000379:h=0005:rn=01:ra=20000000]
D-211420: read fcb        BX=031F CX:0000 DX:005C DI=0327 DS:0087 ES:0087
        FCB:[d=00:n=HELLO   .LST:bn=0000:rs=0080:fs=00000379:h=0005:rn=02:ra=69000000]
D-211430: read fcb        BX=031F CX:0000 DX:005C DI=0327 DS:0087 ES:0087
        FCB:[d=00:n=HELLO   .LST:bn=0000:rs=0080:fs=00000379:h=0005:rn=03:ra=20000000]
D-211420: read fcb        BX=031F CX:0000 DX:005C DI=0327 DS:0087 ES:0087
        FCB:[d=00:n=HELLO   .LST:bn=0000:rs=0080:fs=00000379:h=0005:rn=04:ra=30000000]
D-211430: read fcb        BX=031F CX:0000 DX:005C DI=0327 DS:0087 ES:0087
        FCB:[d=00:n=HELLO   .LST:bn=0000:rs=0080:fs=00000379:h=0005:rn=05:ra=20000000]
D-211420: read fcb        BX=031F CX:0000 DX:005C DI=0327 DS:0087 ES:0087
        FCB:[d=00:n=HELLO   .LST:bn=0000:rs=0080:fs=00000379:h=0005:rn=06:ra=30000000]
D-211400: read fcb        BX=031F CX:0000 DX:005C DI=0327 DS:0087 ES:0087
        FCB:[d=00:n=HELLO   .LST:bn=0000:rs=0080:fs=00000379:h=0005:rn=06:ra=20000000]
D-211400: read fcb        BX=031F CX:0000 DX:005C DI=0327 DS:0087 ES:0087
        FCB:[d=00:n=HELLO   .LST:bn=0000:rs=0080:fs=00000379:h=0005:rn=06:ra=20000000]
D-211400: read fcb        BX=031F CX:0000 DX:005C DI=0327 DS:0087 ES:0087
        FCB:[d=00:n=HELLO   .LST:bn=0000:rs=0080:fs=00000379:h=0005:rn=06:ra=20000000]
```

The last two lines repeat indefinitely.

I tested against dosbox, and i get the expected `AL=0`, `AL=3`, `AL=1` sequence there.

**Comment by dmsc** [comment]
I created 3 test programs to check the behavior, attached is a zip with all the files: [test-fcb.zip](https://github.com/dmsc/emu2/files/7899213/test-fcb.zip)

**Comment by nero** [comment]
Thank you for sacrificing the time to look into it!
