### ISSUE TITLE
HIEW does not respond to input

### ISSUE THREAD

**Issue by johnsonjh** [dmsc/emu2#34]
Haven't looked into the cause yet, however, tested [HIEW 6.50 for DOS](http://www.hiew.ru/) and it doesn't respond to input - but otherwise seems to run.

**Comment by dmsc** [comment]
Hi!

Using `EMU2_DEBUG=int`  I see that the program calls INT-16 AH=11:
```
D-2F1680: BX=0F9F
B-160200: BX=0F9F
B-160200: BX=0F9F
B-160200: BX=0F9F
B-161130: BX=0F9F
UNHANDLED INT 16, AX=1130
D-2F1680: BX=0F9F
```

This is a PS/2 interrupt (not available on earlier BIOS), this is the first time I see a program that needs it.

Will try implementing it, perhaps after that the program will work.

**Comment by johnsonjh** [comment]
Working great - seems that was enough.  Thanks!
