### ISSUE TITLE
Strange behavior with G ... 

### ISSUE THREAD

**Issue by johnsonjh** [dmsc/emu2#36]
All of these issues might be *my* own fault, but, it does work correctly under real DOS (and DOSBox.)

Using the real-mode DOS 8086 version of [G](https://github.com/johnsonjh/g/#binaries):

* Initially no screen is displayed:
  
![49A1070A-9961-41F9-8F5E-97F6F1EB4764](https://user-images.githubusercontent.com/61629094/160201463-99137078-3c11-4613-a399-66e70b7108fa.jpeg)

* Upon a forced repaint (with `!`), quitting fails (via `F7`).

* Pressing ^L to cause a dialog to appear causes that again when trying to exit via F7.

![68AB7991-9A7A-41F9-97B4-8B4CDEC22748](https://user-images.githubusercontent.com/61629094/160201818-975ab68a-a683-401f-8b41-ffccc272b7fd.jpeg)

 * Many other issues that make the editor unusable.

I'll try to look into it myself later tonight (*it's a bit hard on a cell phone*) but there are at least some unhandled interrupt warnings:

![A004C634-E95D-4102-AA19-E5DBA6C5FEA7](https://user-images.githubusercontent.com/61629094/160203260-49c14ab6-5303-4afc-acda-21b7fcdec3f7.jpeg)

It's being built using OpenWatcom - the other builds or a Linux build can be used for reference, but it very much looks like it's simply getting the wrong keyboard input.

**Comment by dmsc** [comment]
Hi!

There are multiple bugs here, first one is the video display:

Handling of full-screen text programs in emu2 is not easy, as I try to support command line programs (that should simply write it's output as a stream), auto-detecting when a given DOS program is trying to write to the screen.

In this case, the editor writes to the screen memory before calling any video bios function. But on the first call of the video functions, the emulator sets the video mode and clears the emulated screen - so the screen is blank.

I think that this is a bug in the program, as you can't expect the video memory to be initialized (or even present) without making any video bios call, but most "newer" DOS programs assume a full PC compatible and MS-DOS is present, so it works.

I can change the emulator to avoid clearing the screen on the first video bios call, and always clear the video memory (but don't set the video mode) on start, this should fix this, and I hope will not break other DOS prograns.

About keyboard handling - I tried the program in DOSBOX and I could not exit, I think that it also does not work ok.

Have Fun!

**Comment by dmsc** [comment]
I just committed a fix for the video issue, but the keyboard issues remain - can you open a new issue for those problems?

Thanks!

**Comment by johnsonjh** [comment]
Will do, thanks!

**Comment by johnsonjh** [comment]
@dmsc 

I meant to check it out further last night, but ended up going right to sleep.

I'll make the new (and improved) issue once I solve a bug or two of my own.

G for DOS can be built in three different flavors. (Four, soon).

From fastest to slowest:

* *Fast-Curses* - 386+ assembly optimized version of *G-Curses*.
* *G-Curses* - Built-in mini-curses support; writes directly to IBM PC-compatible video memory.
* *Curses* - Dependent on an external XSI-compatible curses implementation for DOS, such as PDCurses V3 or PDCursesMod.
* (coming soon) *GT-Curses* - Built-in mini-curses that uses only BIOS calls and user configurable escape sequences. Inefficient, but able work on non-IBM PC-compatible systems. I'm going to initially include terminal definitions for at least DOS ANSI.SYS, and VT100 (to support usage redirected via CTTY or similar.)

The new fourth option is being developed mostly to support a version for 16-bit CP/M (m68k, Z8000, CP/M-86 on non-IBM systems, etc.) but it will be useful for some niche DOS scenarios too.

I've been maintaining this version of G for quite some time, but until this month the DOS versions were neglected and had not been rebuilt since 1995 with no 8086 versions built as of 1993.

I confirmed using 86Box, DOSBox, and DOSBox-X that the 8086 build is buggy in regards to keyboard handling, so this looks like my fault mostly.  All the other builds are fine.

I'm going to take care of this more on my side fist, and if there are remaining problems I'll let you know.

I also checked and verified (using a 1993 and 1995 version of G) that the way the video memory is handled was indeed the historical behavior, so thanks for "fixing" that.

**Comment by johnsonjh** [comment]
@dmsc 

Just for an update, it looks like the remaining G bugs with the 8086 build were caused by OpenWatcom 2 - I cannot replicate the behavior when building with either Microsoft C or Borland C.

**Comment by dmsc** [comment]
Hi!
> 
> Just for an update, it looks like the remaining G bugs with the 8086 build were caused by OpenWatcom 2 - I cannot replicate the behavior when building with either Microsoft C or Borland C.

Great, thanks for testing.

Perhaps you could build the DOS version using gcc-ia16: https://github.com/tkchia/build-ia16/releases (downloadable packages for Linux are here: https://launchpad.net/~tkchia/+archive/ubuntu/build-ia16/ )

Have Fun!

**Comment by johnsonjh** [comment]
I actually regularly build it using IA16-GCC, but it isn't working yet, as they don't yet support the large memory model (medium isn't enough with a lot of trimming).

**Comment by johnsonjh** [comment]
@dmsc 

I have a `make test` script that does various builds - doesn't yet automate build testing with Microsoft C or Borland C via DOS, but that is on my list of things to do.

(If Microsoft C 7 didn't require 32-bit DPMI services, and Borland C 5.02 didn't use a 32-bit DOS extender, I'd use them in emu2; DOSEMU2 works well enough.)

The current test script out looks like ... 

```text
################################################################################
## GNU/Linux: GCC, Native:

+ gcc -Os -fno-stack-protector -U_FORTIFY_SOURCE
   -Wno-int-to-pointer-cast -flto -fdata-sections -ffunction-sections g.c
   -o g -flto -Wl,--gc-sections -lcurses
+ OK! [92KiB] g: ELF 64-bit LSB executable, x86-64, version 1 (SYSV),
   dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for
   GNU/Linux 3.2.0, stripped

################################################################################
## GNU/Linux: GCC, Tiny, Native:

+ gcc -DTINY_G=1 -Os -fno-stack-protector -U_FORTIFY_SOURCE
   -Wno-int-to-pointer-cast -flto -fdata-sections -ffunction-sections g.c
   -o g -flto -Wl,--gc-sections -lcurses
+ OK! [80KiB] g: ELF 64-bit LSB executable, x86-64, version 1 (SYSV),
   dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for
   GNU/Linux 3.2.0, stripped

################################################################################
## GNU/Linux: Clang, Native:

+ clang -Oz -fno-stack-protector -U_FORTIFY_SOURCE
   -Wno-int-to-pointer-cast -flto -fdata-sections -ffunction-sections g.c
   -o g -flto -Wl,--gc-sections -lcurses
+ OK! [92KiB] g: ELF 64-bit LSB executable, x86-64, version 1 (SYSV),
   dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for
   GNU/Linux 3.2.0, stripped

################################################################################
## GNU/Linux: PCC, Native:

+ pcc -D_BITS_WCHAR_H=1 -Os -fno-stack-protector -U_FORTIFY_SOURCE
   -Wno-int-to-pointer-cast -flto -fdata-sections -ffunction-sections g.c
   -o g -flto -Wl,--gc-sections -lcurses
+ OK! [112KiB] g: ELF 64-bit LSB executable, x86-64, version 1 (SYSV),
   dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for
   GNU/Linux 3.2.0, stripped

################################################################################
## GNU/Linux: Oracle Studio, Native:

+ suncc -O -xspace -U_FORTIFY_SOURCE -Wno-int-to-pointer-cast g.c -o
   g -lcurses
+ OK! [160KiB] g: ELF 64-bit LSB executable, x86-64, version 1 (SYSV),
   dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, stripped

################################################################################
## DOS: OpenWatcom, 8086:

+ env WATCOM=/opt/watcom INCLUDE=/opt/watcom/h wcl -k32767 -l=DOS
   -bcl=DOS -DDOS=1 -DASM86=0 -0 -ml -fpi -zm @g.lnk -d0 -s -zq -oabls
   -zp2 -fe=g86.exe g.c
+ OK! [116KiB] g86.exe: MS-DOS executable

################################################################################
## DOS: OpenWatcom, 386, Real mode:

+ env WATCOM=/opt/watcom INCLUDE=/opt/watcom/h wcl -k32767 -l=DOS
   -bcl=DOS -DDOS=1 -DASM86=1 -3 -ml -fpi -zm @g.lnk -d0 -s -zq -oabls
   -zp2 -fe=g386r.exe g.c
+ OK! [112KiB] g386r.exe: MS-DOS executable

################################################################################
## DOS: OpenWatcom, 386, Protected:

+ env WATCOM=/opt/watcom INCLUDE=/opt/watcom/h wcl386 -l=DOS32A -bt=DOS
   -DDOS=1 -DASM86=0 -3r -mf -fpi -zm @g.lnk -k32767 -d0 -s -zq -oabls
   -zp2 -DWCL386=1 -fe=g386p.exe g.c
+ OK! [168KiB] g386p.exe: MS-DOS executable, LE executable for MS-DOS,
   DOS/32A DOS extender (embedded)

################################################################################
## DOS: DJGPP, 386, Curses, Protected:

+ Building PdCursesMod: OK.
+ /opt/djgpp/bin/i586-pc-msdosdjgpp-gcc -march=i386 -Wno-attributes
   -I…/src/PDCursesMod -Os -fno-stack-protector -U_FORTIFY_SOURCE
   -Wno-int-to-pointer-cast -flto -fdata-sections -ffunction-sections g.c
   -o gt.exe -flto -Wl,--gc-sections …/src/PDCursesMod/dos/pdcurses.a
+ /opt/djgpp/bin/i586-pc-msdosdjgpp-strip -s ./gt.exe
+ exe2coff ./gt.exe
+ cat /opt/cwspdmi/cwsdstub.exe ./gt
+ OK! [256KiB] g386.exe: MS-DOS executable, COFF for MS-DOS, DJGPP go32
   DOS extender

################################################################################
## DOS: IA16-GCC, 8086:

+ …/src/build-ia16/prefix/bin/ia16-elf-gcc -march=i8086
   -mregparmcall -mcmodel=medium -DDOS=1 -UUNIX -Os -fno-stack-protector
   -U_FORTIFY_SOURCE -Wno-int-to-pointer-cast g.c -o g.exe -li86
+ OK! [132KiB] g.exe: MS-DOS executable

################################################################################
## DOS: IA16-GCC, 8086, Curses:

+ …/src/build-ia16/prefix/bin/ia16-elf-gcc -march=i8086 -mregparmcall
   -mcmodel=medium -UDOS -DUNIX=1 -DTINY_G=1 -Os -fno-stack-protector
   -U_FORTIFY_SOURCE -Wno-int-to-pointer-cast g.c -o g.exe -lpdcurses -li86
+ OK! [148KiB] g.exe: MS-DOS executable

################################################################################
## OS/2: OpenWatcom, 286, Curses, Protected mode:

+ Building PdCursesMod: OK.
+ env WATCOM=/opt/watcom
   INCLUDE=/opt/watcom/h:/opt/watcom/h/os21x:…/src/PDCursesMod wcl
   -l=OS2 -bcl=OS2 -UDOS -DUNIX=1 -2 -ml -fpi -zm @gos2.lnk -k32767
   -d0 -s -zq -oabls -D_TIMESPEC_DEFINED -za -zp2 -fe=g286p.exe g.c
   …/src/PDCursesMod/os2/pdcurses.lib
+ OK! [152KiB] g286p.exe: MS-DOS executable, NE for OS/2 1.x (EXE)

################################################################################
## OS/2: OpenWatcom, 386, Curses, Protected mode:

+ Building PdCursesMod: OK.
+ env WATCOM=/opt/watcom
   INCLUDE=/opt/watcom/h:/opt/watcom/h/os2:…/src/PDCursesMod wcl386
   -l=OS2V2 -bcl=OS2V2 -UDOS -DUNIX=1 -3r -mf -fpi -zm @gos2.lnk
   -k32767 -d0 -s -zq -oabls -D_TIMESPEC_DEFINED -zp2 -fe=gos2p.exe g.c
   …/src/PDCursesMod/os2/pdcurses.lib
+ OK! [140KiB] gos2p.exe: MS-DOS executable, LX for OS/2 (console)
   i80386

## Tests completed successfully
```
