### ISSUE TITLE
Incorrect video display with Calvin v2.3

### ISSUE THREAD

**Issue by johnsonjh** [dmsc/emu2#38]
[Calvin](http://archives.scovetta.com/pub/simtelnet/msdos/editor/calvin23.zip) works with DOSEMU2 and DOSBox-X (including resizing under DOSEMU2), but the display is corrupted and it doesn't seem to respond to input.

Some warnings:
```
UNHANDLED INT 09, AX=273a
UNHANDLED INT 09, AX=1c0d
UNHANDLED INT 09, AX=1071
```

**Comment by dmsc** [comment]
Problem was that this editor writes directly to BIOS memory to set cursor coordinates before calling bios to write characters, so I added code to read the cursor position from BIOS memory on each call the uses the position.

Have Fun!
