### ISSUE TITLE
IBM FileCommand II paints a blue screen and does not continue

### ISSUE THREAD

**Issue by johnsonjh** [dmsc/emu2#40]
* [**IBM FileCommand II**](https://winworldpc.com/product/filecommand/ii) paints a blue screen and does not continue. 

  Moved from https://github.com/dmsc/emu2/issues/39

**Comment by johnsonjh** [comment]
From @dmsc in the other thread:

> This programs loops reading the CGA registers, counting the horizontal retraces, currently emu2 simply fakes the values, so it won't work without some complex video emulation.

**Comment by dmsc** [comment]
Note that the program still does not work, as it really is a TSR.
