### ISSUE TITLE
Advice Required: Compatibility List (When and how is your emulator used)

### ISSUE THREAD

**Issue by tsupplis** [dmsc/emu2#53]
It would be super cool to have examples of usage and a form of compatibility list where people can contribute? any thought?

**Comment by johnsonjh** [comment]
GitHub Wiki Page?

**Comment by dmsc** [comment]
I could open-up the github wiki to contribute instructions to run useful programs.

About the intended scope of EMU2: running text-mode DOS applications in modern Unix systems as native utilities.

I originally wrote emu2 to simply run PALASM and onther old DOS compilers, and grw from there to fully support text mode IDEs.

Have Fun!

**Comment by tsupplis** [comment]
That would be cool.
I use emu2 extensively for cross compilation (including work on CP/M-86 and DOS 1.1 and normal DOS)

**Comment by dmsc** [comment]
I added a basic wiki page, and invited you as a collaborator, so you can edit it further.

Thanks!

**Comment by dmsc** [comment]
Hi!

> Could you add me as well? I could contribute instructions for various applications.

Done, thank you!

Should I make the wiki edition public? I don't know how github prevents vandalism on wikis, so I don't know if that is appropriate.

**Comment by johnsonjh** [comment]
I'm not too familiar with GitHub wiki's - I mostly use and prefer GitLab.

I expect it's similar, but I'd have to look at it myself.
