### ISSUE TITLE
No stdout output running under node-pty

### ISSUE THREAD

**Issue by NuSkooler** [dmsc/emu2#55]
I'm attempting to use `emu2` to run some old text mode DOS applications under https://github.com/microsoft/node-pty for the purpose of a BBS "door". Essentially I launch `emu2` under `node-pty`'s `spawn()` and capture `stdout`. Input from the user is sent to `stdin`.

Currently I'm trying this with [Sleuth](https://www.myabandonware.com/game/sleuth-1uv). When run from a standard Linux terminal, everything is fine. When run as described as above, I do not get any output.

I use the same technique for launching native OS binaries without issue.

Any ideas? I can provide any of the debug logs if they would be helpful.

**Comment by NuSkooler** [comment]
Well now I feel stupid, but setting up `scroll.zip` gave me a eye check. I had both a typo and a bug in my code not catching the bad configuration. Both are fixed now and `emu2` + Sleuth are working great.

Thank you!

**Comment by dmsc** [comment]
Hi!

> Well now I feel stupid, but setting up `scroll.zip` gave me a eye check. I had both a typo and a bug in my code not catching the bad configuration. Both are fixed now and `emu2` + Sleuth are working great.
> 
> Thank you!

Great, glad I could help!
