### ISSUE TITLE
DOS string output does not expand tabs

### ISSUE THREAD

**Issue by nero** [dmsc/emu2#60]
The MS-DOS 3.2 DEBUG.EXE renders a circle ○ (character 9 of the current codepage) instead of whitespace in some places. During launch, it queries Int 10,AH=0Fh (get current video mode) and thus switches its output into video mode. For console writes, it uses Int 21,AH=40h (write to file or device). The code in `dos.c` for that syscall loops over the bytes and sends them to `video_putch()`. `video_putch()` does not expand tab characters.

Since im using a original PC1512 binary, i consulted the documentation of the original BIOS that the program was meant to run under. From http://www.seasip.info/AmstradXT/1512tech/section2.html#2.3.7.14:

> The following display characters are executed rather than displayed symbolically:
> 
> BEL (07h)
>     Sounds a short (bleep) tone on the speaker.
> BS (08h)
>     Decrements the cursor column one character position unless the column is already zero in which case it is ignored.
> CR (0Dh)
>     Sets the cursor column address to zero.
> LF (0Ah)
>     Increments the cursor row address by one and follows the scroll up procedure as detailed in the paragraph above.
> 
> All other control characters are displayed.

TAB (09h) is not mentioned, so i assume that `video_putch()` is right to not implement it.

In the RBIL on INT 21,AH=02h i found a hint about where tab is implemented. From http://www.ctyme.com/intr/rb-2554.htm:

> The last character output will be the character in DL unless DL=09h on entry, in which case AL=20h as tabs are expanded to blanks.

So in the real DOS, its likely the CON device driver doing the expansion from tabs to spaces.

Program to reproduce:

```
; switch output into video mode by doing harmless use of int 10h
mov ah, f
int 10
; print a tab
mov ah, 2
mov dl, 9
int 21
; exit
int 20
```

On emu2, the above program prints a ○ instead of the expected whitespaces.

**Comment by dmsc** [comment]
Thank you for the detailed analysis.

Made two commits to actually fix this, as DEBUG was using buffered output to the console.

Have Fun!
