### ISSUE TITLE
Strange bugs with DND 2.01

### ISSUE THREAD

**Issue by johnsonjh** [dmsc/emu2#62]
Noticed a few strange issues with DND 2.0.1 (1988), which was written in Turbo C.

Interestingly, these bugs don't affect the earlier DND 1.2.1 (1987), which was written in Microsoft Pascal.

You can get DND 2.0.1 [here](https://archive.org/download/DnddosGame/Dnd-DungeonsOfTheNecromancersDomainV2.0.1sw1988r.o.Softwarerole-playingrpg.zip).  Start with a clean players file by removing the PLAYERS.DND files.

To reproduce the issue:

1. Start DND
2. [`C`]reate a new character and enter the Dungeon.
3. [`K`]ill yourself.
4. [`P`]rint all characters

DOSEMU:

![Screenshot from 2024-07-01 13-41-50](https://github.com/dmsc/emu2/assets/61629094/d88dc47a-11c1-43c3-9a66-d66e75bd2e10)

emu2:

![Screenshot from 2024-07-01 13-42-18](https://github.com/dmsc/emu2/assets/61629094/da9f347d-71bd-41b1-8a1e-282857fc03d1)

As you can see, in DOSEMU with real DOS, the character is deleted.

In emu2, the character is not deleted, and in fact, the character never "dies" allowing you to *cheat* in the game, continuing along after death.

You can also now a new character, [`Q`]uit the dungeon:

DOSEMU:
 
![Screenshot from 2024-07-01 13-45-23](https://github.com/dmsc/emu2/assets/61629094/3bf47eba-5eb9-4d6b-a57f-864893351a83)

emu2:

![Screenshot from 2024-07-01 13-45-39](https://github.com/dmsc/emu2/assets/61629094/de05a0db-093c-4542-9644-ffca0f721509)

And now from the DND menu, [`K`]ill the new character, and [`P`]rint the characters.

In DOSEMU, now characters remain, which is correct, but in emu2, you now have two of the original characters, like this:

![Screenshot from 2024-07-01 13-47-46](https://github.com/dmsc/emu2/assets/61629094/f79e2244-9bdd-41ce-b844-7feaa4ad842d)

A quick examination of the players file shows the emu2 version is corrupted, having two copies of the character, which should be impossible:
```sh
$ strings ~/.dosemu/drive_c/dnd201/players.dnd 
$ strings ./players.dnd                         
Raven
raven
ANCALAGN.DGN
Raven
raven
ANCALAGN.DGN
```

There are a few minor cosmetic issue as well:
* The screen is not correctly cleared after using the various menus and when entering the dungeon.
* When entering invalid keys at the menus, a `•` is displayed, like this, where real DOS displays nothing at all:

![Screenshot from 2024-07-01 13-54-57](https://github.com/dmsc/emu2/assets/61629094/a2520d42-38fa-462f-8d6a-1e6008df8445)
 

I've not had time to look at it myself, and while it might be a bug in the game, the game always malfunctions under emu2 this way, but never in real DOS (tested dosbox, dosemu, and DOS under KVM).

**Comment by dmsc** [comment]
Hi!

Thanks for the bug report. I will try to investigate - my first run produced a DOS debug log of 1GB!

**Comment by dmsc** [comment]
Hi again.

I pushed a fix for the save-file bugs, the emulator missed that you can truncate a file via a write call.

You can open a new bug for the screen corruption issues.

Thanks!

**Comment by dmsc** [comment]
OK, that last commit should fix the extra dots on invalid input, now the terminal should make a sound.

About clearing the screen, the game don't really clears the screen, it only scrolls it assuming a 80x25 window - but emu2 tries to preserve as much as possible of the screen state (to make it usable on a terminal), so it never clears lines that are not visible anymore.
