### ISSUE TITLE
VEDIT PLUS Ver. 2.33b (4/27/87) “ED” command weirdness

### ISSUE THREAD

**Issue by johnsonjh** [dmsc/emu2#67]
* In VEDIT PLUS Ver. 2.33b, using the “ED” command to list the directory results in odd output that does not happen in real DOS under DOSEMU.  \
\
(You can enter command mode with ESC-e or ESC-ESC, start VEDIT with `VEDIT ---`, or use INSTALL to configure VEDIT to start in command mode.  *Be sure to configure the ANSI X3.64 [10] terminal type*):

```
COMMAND: ev
VEDIT PLUS Ver. 2.33b  4/27/87
COMMAND: ed

DIRECTORY C:\
EDIT.I^CC.OMP  EDIT.I^CC.V20  EDIT.I^CE.RRA  EDIT.I^CI.NST
EDIT.I^CI.NST  EDIT.I^CI.NTM  EDIT.I^CK.EYS  EDIT.I^CM.ENU
EDIT.I^CM.ENU  EDIT.I^CP.RIN  EDIT.I^CR.EAD  EDIT.I^CR.EAD
EDIT.I^CS.ORT  EDIT.I^CV.EDI  EDIT.I^CV.PLU  EDIT.I^CW.HAT

COMMAND: eq
ABANDON FILE (Y/N)? y
```

* As an aside, starting INSTALL from 4DOS (https://4dos.info/4dvers/4dos800.zip) results in the input not working properly and the INSTALL prompt being printed in an infinite loop.  I can open a separate issue for this if preferred.

**Comment by johnsonjh** [comment]
FWIW, in the older VEDIT 1.40, this works:
```
$ emu2 vedit.com

VEDIT Ver. 1.40

Copyright (C) 1985 CompuView Products, Inc.

Welcome to VEDIT

"EX" to Exit, "EQ" to Quit, "V" to Edit, "H" or "EH" for Help

COMMAND: ed
AUTOLOAD.DOC  INSTALL .EXE  INSTALL .INI  INTMOD  .EXE
NEWCRT  .DOC  PRINT   .EXC  READCRT .DOC  VEDIT   .COM
VEDIT86C.SET  VEHELP  .HLP  VHELP   .HLP  VVHELP  .HLP

COMMAND:
```

**Comment by dmsc** [comment]
Hi!

VEDIT never does screen handling, it writes directly to the console using ANSI codes. This means that your terminal receives the control codes and interprets the codes directly, you can verify this by running `emu2 vedit.com > test`, you will see all the ANSI codes in the `test` file.

In real DOS this only works if you install the "ansi.sys" device driver, but EMU2 does not emulate this device, as it will mean loosing the ability to redirect terminal output. Perhaps this could be added as a startup option, for the very few cases of programs doing full-screen ANSI terminal handling.

Nevertheless, there is still something strange going on, as VEDIT prints the "EDIT" word in front of all entries - I will investigate.

**Comment by johnsonjh** [comment]
Something strange is afoot for sure, because the output sometimes becomes different if you use the “2ED” “3ED” and “4ED” commands, followed by “ED” again.  For example showing “DIT” or “ITN” starting instead of “EDIT”.  It’s really weird.

Real DOS is fine.

Also the names shown aren’t exactly mangled by just the beginning parts being overwritten - the extension shown is actually the beginnings of the filenames (minus the first letter).

![IMG_0203](https://github.com/user-attachments/assets/0d2323ac-d911-4fdf-be4e-0b0725d7b6c0)

I guess VEDIT is a “good” program for finding DOS  bug-compatibility. :)

**Comment by johnsonjh** [comment]
Also, I’m happy enough with relying on xterm or gnome-terminal when using the “ANSI X3.64” configuration option, no real need for emu2 to interpret anything directly, I don’t think.
