### ISSUE TITLE
Int 21h function 26h/38 not implemented

### ISSUE THREAD

**Issue by tsupplis** [dmsc/emu2#7]
I noticed that function 26h was currently not implemented.

Here is the snippet:
```
    case 0x26: // Create PSP (allocate segment (singleton), and copy PSP)
    {
        uint8_t *new_base = getptr(cpuGetAddress(cpuGetDX(),0), 0x100);
        uint8_t *orig = getptr(cpuGetAddress(get_current_PSP(),0), 0x100);
        // Copy PSP to the nex segment, 0x80 is what DOS does)
        memcpy(new_base,orig,0x80);
        debug(debug_dos, "\tnew psp segment %04x.\n", cpuGetDX());
        debug(debug_dos, "\tnew psp size %02x%02x.\n", new_base[7],new_base[6]);        
        debug(debug_dos, "\toriginal psp segment %04x.\n", get_current_PSP());
        debug(debug_dos, "\toriginal psp size %02x%02x.\n", orig[7],orig[6]);        
        break;
    }
```
As for the FCB problem, very happy to create a PR if you prefer.

**Comment by tsupplis** [comment]
So to follow give you a way to test a rare application using it....
https://github.com/microsoft/MS-DOS/blob/master/v1.25/source/HEX2BIN.ASM
Attached below a compiled version of it...

[hex2bin.zip](https://github.com/dmsc/emu2/files/4535666/hex2bin.zip)

**Comment by dmsc** [comment]
Thanks!

I pushed a slightly edited version of this change, see b02b093dde12a078d5f6bd187da0f346d9e71d19
