### ISSUE TITLE
MS-DOS EDIT 2.0.026 doesn't respond correctly to keyboard input.

### ISSUE THREAD

**Issue by johnsonjh** [dmsc/emu2#70]
![Screenshot From 2024-10-04 22-54-05](https://github.com/user-attachments/assets/1aacc57b-052a-4694-a9fc-17aa2152a9cd)

[EDIT20026.ZIP](https://github.com/user-attachments/files/17264854/EDIT20026.ZIP)

**Comment by dmsc** [comment]
BTW, thank you for all the bug reports!

**Comment by johnsonjh** [comment]
@dmsc 

Hopefully I’m not driving you nuts!

**Comment by dmsc** [comment]
Hi!
> 
> Hopefully I’m not driving you nuts!

No! :) 

But I do think this should use a proper regression test, so that fixing one program does not break another.
