### ISSUE TITLE
VEDIT PLUS 2.33b poor performance

### ISSUE THREAD

**Issue by johnsonjh** [dmsc/emu2#71]
VEDIT PLUS 2.33b has *very* poor performance in emu2.

I made a quick video of using the same VEDIT binary (configured for ANSI) in 86box with MS-DOS 6.22 running with the ANSI-PLUS driver, and then in emu2 in gnome-terminal, on the same system, and you can see the large performance difference.

https://github.com/user-attachments/assets/552bed71-d6a1-47be-bc4b-4c6fce3e1548

In both cases I just did a few Page Up and Page Down operations.  Only visual mode is slow - response is instant in command mode in emu2.

Binary, as configured, attached: [vedit.com.gz](https://github.com/user-attachments/files/17267996/vedit.com.gz)

Edit: I forgot to adjust the gnome-terminal window up an additional row to compensate for the tmux status line, so the last line is overwritten wrongly when scrolling, however, this doesn't affect the demonstration of the performance difference between emulated real DOS and emu2.

**Comment by dmsc** [comment]
Hi!

emu2 detects when an application repeatedly reads the keyboard and sleeps for a while, to avoid the app using all the CPU.

Currently, this is an arbitrary limit of 4 reads each 10ms, after this, the emulator sleeps for 10ms to allow for any input activity.

VEDIT.COM reads the keyboard before printing any character to the screen, so with current emu2, the drawing is limited to 4 characters per 10ms, or 400 characters per second. As each ANSI control character needs many characters, the speed is really slow.

I will adjust the code to allow for more reads, but this probably needs a better heuristic.

**Comment by johnsonjh** [comment]
Makes sense.  

There actually is a version of VEDIT 1.X and 2.X that does support the memory mapped video I/O directly, which is of course much faster, but I unfortunately don’t have that version.

VEDIT ran on many many different OSs and platforms and is very portable.  It was actually the first third-party program available for 86-DOS so it worked on non-IBM PC compatible DOS machines.

Reading the keyboard that often seems like it would be a good hack if the reading code is fast but the output part of the BIOS is slow, so you can type ahead, scroll, and do many operations before the whole screen has redraw.
