### ISSUE TITLE
src/dis.c:826:1: warning: non-void function does not return a value in all control paths [-Wreturn-type]

### ISSUE THREAD

**Issue by johnsonjh** [dmsc/emu2#80]
Warning when building with current Clang and GCC:

```c
src/dis.c:826:1: warning: non-void function does not return a value in all control paths [-Wreturn-type]
```

**Comment by dmsc** [comment]
Hi!

This was disused here: https://github.com/dmsc/emu2/pull/58

The majority vote was to keep the code as is, as current GCC versions do check all control paths correctly and do not emit this warning.

Have Fun!

**Comment by johnsonjh** [comment]
No problem - I am seeing this warning in current GCC 14.2.1 however

**Comment by dmsc** [comment]
Hi!

> No problem - I am seeing this warning in current GCC 14.2.1 however

Strange, here with the same GCC it does not show the warning - perhaps due to the compilation options?

![image](https://github.com/user-attachments/assets/c8c57804-2973-4b95-888f-437c71ba95fc)

**Comment by johnsonjh** [comment]
Probably distribution differences in the default warnings they enable…

I won’t worry about it too much :)
