### ISSUE TITLE
`CLS` and `COPY` hangs on MS-DOS 6.22's `COMMAND.COM`

### ISSUE THREAD

**Issue by johnsonjh** [dmsc/emu2#93]
`CLS` and `COPY` hang on MS-DOS 6.22's `COMMAND.COM`

Not a deal breaker since I just removed the `CLS` and manually copied the files I needed (from an installer that uses a lot of batch).

Might be related to `XCOPY` which also doesn't work, as it always reports "`0 File(s) copied.`"

**Comment by dmsc** [comment]
Hi!

I saw this when testing `COMMAND.COM` yesterday.

I will need to investigate, but the DOS 6.22 command calls on some later functions that emu2 does not implement (yet?). For example, doing a simple DIR returns an extended error, the correct return value is not documented in the intlist.

**Comment by johnsonjh** [comment]
I saw that error too.  Seems to be something with getting the free space.  I'll have more time to poke at it this weekend.
