### ISSUE TITLE
MS-DOS 5 `EDLIN` reports `File Creation Error`

### ISSUE THREAD

**Issue by johnsonjh** [dmsc/emu2#95]
MS-DOS `EDLIN` reports `File Creation Error` (seemingly even when trying to open an existing file).

**Comment by dmsc** [comment]
Hi!

This is for DOS 5 EDLIN, the DOS 3.3 version does seem to work.

The problem is that EDLIN calls INT 21/6C, that noly exists on DOS 4 and upwards, "EXTENDED OPEN/CREATE". I suspect that no other program uses this call :-)

I will try to implement it when I have more time.

Have Fun!
